name: Eleveny build and Cloudflare deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Eleventy build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npx eleventy

  deploy:
    name: Cloudflare Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
