name: Deploy to Cloudflare

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Build Eleventy assets
        run: |
          npm ci
          npx eleventy
      - name: Deploy assets to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.42.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
